# Generated by Django 2.2.5 on 2019-11-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.URLField(help_text="Please enter the url of your company's facebook")),
                ('youtube_url', models.URLField(help_text="Please enter the url of your company's youtube")),
                ('instagram_url', models.URLField(help_text="Please enter the url of your company's instagram")),
                ('twitter_url', models.URLField(help_text="Please enter the url of your company's twitter")),
                ('short_detail', models.CharField(blank=True, max_length=600, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
