# Generated by Django 2.2.5 on 2019-11-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_contactdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('video', models.URLField(help_text='Please enter the url of the video from youtube or other sources')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AwardList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_title', models.CharField(blank=True, max_length=200, null=True)),
                ('award_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon/')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('person_image', models.ImageField(blank=True, null=True, upload_to='testimonial/')),
                ('person_name', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactDetail',
        ),
        migrations.RemoveField(
            model_name='companyintroduction',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='companyintroduction',
            name='company_name',
        ),
        migrations.AddField(
            model_name='companydetail',
            name='company_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='company_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='facebook_url',
            field=models.URLField(blank=True, help_text="Please enter the url of your company's facebook", null=True),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='instagram_url',
            field=models.URLField(blank=True, help_text="Please enter the url of your company's instagram", null=True),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='short_detail',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='twitter_url',
            field=models.URLField(blank=True, help_text="Please enter the url of your company's twitter", null=True),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='youtube_url',
            field=models.URLField(blank=True, help_text="Please enter the url of your company's youtube", null=True),
        ),
        migrations.AddField(
            model_name='companyintroduction',
            name='mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyintroduction',
            name='strategy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyintroduction',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
