# Generated by Django 2.2.5 on 2019-11-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_rabbitbreed_rabbitcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rabbitbreed',
            name='category',
        ),
        migrations.AddField(
            model_name='rabbitbreed',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='RabbitCategory',
        ),
    ]
