# Generated by Django 2.2.5 on 2019-11-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_farmingequipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopNow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
