# Generated by Django 2.2.5 on 2019-11-06 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_shopnow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rabbitbreed',
            old_name='image',
            new_name='main_image',
        ),
        migrations.CreateModel(
            name='RabbitSubImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rabbit/')),
                ('rabbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rabbit', to='item.RabbitBreed')),
            ],
        ),
    ]
