# Generated by Django 2.2.5 on 2019-11-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_rabbitdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='worktogether',
            old_name='title',
            new_name='heading',
        ),
        migrations.AlterField(
            model_name='rabbitbreed',
            name='price',
            field=models.IntegerField(blank=True, help_text='Rs.', null=True),
        ),
    ]
