# Generated by Django 2.2.5 on 2019-11-08 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_for_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkTogether',
        ),
    ]
