# Generated by Django 2.2.5 on 2019-11-08 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_delete_worktogether'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='For',
            new_name='WorkFor',
        ),
        migrations.RenameModel(
            old_name='Together',
            new_name='WorkTogether',
        ),
    ]
