# Generated by Django 2.2.5 on 2019-11-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0017_auto_20191108_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='short description about the recipe', null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('recipe_preparation', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipe/')),
            ],
        ),
    ]
