# Generated by Django 2.2.5 on 2019-11-10 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0020_auto_20191110_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageservice',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='item.Package'),
        ),
    ]
