# Generated by Django 2.2.5 on 2019-11-10 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0021_packageservice_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='plan_name',
            new_name='package_name',
        ),
    ]
