# Generated by Django 2.2.5 on 2019-12-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0026_orderinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
