# Generated by Django 2.2.5 on 2019-12-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0028_whatwedo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatwedo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whatwedo',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
