# Generated by Django 2.2.5 on 2019-12-20 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0029_auto_20191220_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnership',
            old_name='title',
            new_name='company_name',
        ),
    ]
