# Generated by Django 2.2.5 on 2019-12-20 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0030_auto_20191220_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnership',
            name='heading',
        ),
    ]
