# Generated by Django 2.2.5 on 2019-12-22 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0031_remove_partnership_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='heading',
        ),
    ]
