# Generated by Django 2.2.5 on 2019-12-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0032_remove_testimonial_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='service_detail/'),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
