# Generated by Django 2.2.5 on 2019-12-22 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0033_auto_20191222_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepackage',
            name='price',
        ),
    ]
