# Generated by Django 2.2.5 on 2019-12-22 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0034_remove_servicepackage_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_package', to='item.Service'),
        ),
        migrations.DeleteModel(
            name='ServicePackage',
        ),
    ]
