# Generated by Django 2.2.5 on 2019-12-22 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0035_auto_20191222_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageservice',
            name='plan',
        ),
        migrations.AddField(
            model_name='packageservice',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package', to='item.Package'),
        ),
    ]
