# Generated by Django 2.2.5 on 2019-12-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0036_auto_20191222_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='title',
        ),
    ]
