# Generated by Django 2.2.5 on 2019-12-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0038_auto_20191222_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabbitmeat',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Female')], max_length=100, null=True),
        ),
    ]
