# Generated by Django 2.2.5 on 2019-12-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0039_rabbitmeat_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabbitmeat',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True),
        ),
    ]
