# Generated by Django 2.2.5 on 2019-12-22 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0041_auto_20191222_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='short description', null=True)),
                ('price', models.IntegerField(blank=True, help_text='Rs. per kg', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='meat/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='item.Category')),
            ],
        ),
        migrations.DeleteModel(
            name='RabbitMeat',
        ),
    ]
