# Generated by Django 2.2.5 on 2019-12-22 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0042_auto_20191222_1609'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryDetail',
            new_name='Detail',
        ),
    ]
