# Generated by Django 2.2.5 on 2019-12-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0043_auto_20191222_1630'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail',
            new_name='CategoryDetail',
        ),
    ]
