# Generated by Django 2.2.5 on 2019-12-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0044_auto_20191222_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
    ]
