# Generated by Django 2.2.5 on 2019-12-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0045_auto_20191223_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
