# Generated by Django 2.2.5 on 2019-12-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0046_questioncategory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('N', 'News'), ('E', 'Event')], max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
