# Generated by Django 2.2.5 on 2019-12-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0049_auto_20191223_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('News', 'News'), ('Event', 'Event')], max_length=100, null=True),
        ),
    ]
