# Generated by Django 2.2.5 on 2019-12-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0052_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='offer/')),
            ],
        ),
    ]
