# Generated by Django 2.2.5 on 2019-12-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0054_workfor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stories',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='stories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='story/'),
        ),
        migrations.AddField(
            model_name='stories',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
