# Generated by Django 2.2.5 on 2019-12-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0055_auto_20191229_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydetail',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], help_text='If rabbit choose anyone', max_length=1, null=True),
        ),
    ]
