# Generated by Django 2.2.5 on 2020-01-02 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0056_categorydetail_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydetail',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail/'),
        ),
        migrations.CreateModel(
            name='ProductSubImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rabbit/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='item.CategoryDetail')),
            ],
        ),
    ]
