# Generated by Django 2.2.5 on 2020-01-02 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0058_productdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail_product', to='item.CategoryDetail'),
        ),
    ]
