# Generated by Django 2.2.5 on 2020-01-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0059_productdetail_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FarmingEquipment',
        ),
        migrations.RemoveField(
            model_name='rabbitdetail',
            name='rabbit',
        ),
        migrations.RemoveField(
            model_name='rabbitsubimage',
            name='rabbit',
        ),
        migrations.RemoveField(
            model_name='categorydetail',
            name='small_image',
        ),
        migrations.RemoveField(
            model_name='productsubimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productsubimage',
            name='big_image',
            field=models.ImageField(blank=True, null=True, upload_to='productsub/'),
        ),
        migrations.AddField(
            model_name='productsubimage',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='productthumb'),
        ),
        migrations.DeleteModel(
            name='RabbitBreed',
        ),
        migrations.DeleteModel(
            name='RabbitDetail',
        ),
        migrations.DeleteModel(
            name='RabbitSubImage',
        ),
    ]
