# Generated by Django 2.2.5 on 2020-01-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0061_auto_20200103_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydetail',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], help_text='If rabbit choose anyone', max_length=100, null=True),
        ),
    ]
