# Generated by Django 2.2.5 on 2020-01-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0062_auto_20200103_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydetail',
            name='unit',
            field=models.CharField(blank=True, help_text='Please enter the unit eg. kg, piece etc', max_length=100, null=True),
        ),
    ]
