# Generated by Django 2.2.5 on 2020-01-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0063_categorydetail_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydetail',
            name='price',
            field=models.IntegerField(blank=True, help_text='Rs. per', null=True),
        ),
    ]
