# Generated by Django 2.2.9 on 2020-01-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0065_service_detail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyintroduction',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='intro/main'),
        ),
    ]
