# Generated by Django 2.2.9 on 2020-01-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0067_auto_20200115_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='thumbnail_image',
            field=models.ImageField(blank=True, help_text='Image Size: width=559px, height=487px', null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, help_text='Image Size: width=360px, height=295px', null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='categorydetail',
            name='image',
            field=models.ImageField(blank=True, help_text='Image Size: width=360px, height=295px', null=True, upload_to='meat/'),
        ),
        migrations.AlterField(
            model_name='companyintroduction',
            name='image',
            field=models.ImageField(blank=True, help_text='Image Size: width=220px, height=216px', null=True, upload_to='intro/'),
        ),
        migrations.AlterField(
            model_name='companyintroduction',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Image Size: width=420px, height=568px', null=True, upload_to='intro/main'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Image Size: width=393px, height=272px', null=True, upload_to='event/'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(help_text='Image Size: width=262px, height=489px', upload_to='offer/'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='Image Size: width=1459px, height=1042px', null=True, upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='program',
            name='image',
            field=models.ImageField(help_text='Image Size: width=650px, height=464px', upload_to='program/'),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Image Size: width=700px, height=350px', null=True, upload_to='quecategory/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Image Size: width=360px, height=295px', null=True, upload_to='recipe/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='detail_image',
            field=models.ImageField(blank=True, help_text='Image Size: width=700px, height=350px', null=True, upload_to='image/detail_img'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Image Size: width=360px, height=249px', null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='icon',
            field=models.ImageField(blank=True, help_text='Image Size: width=40px, height=40px', null=True, upload_to='service_detail/'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='image',
            field=models.ImageField(blank=True, help_text='Image Size: width=263px, height=271px', null=True, upload_to='story/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='person_image',
            field=models.ImageField(blank=True, help_text='Image Size: width=250px, height=216px', null=True, upload_to='testimonial/'),
        ),
        migrations.AlterField(
            model_name='whatwedo',
            name='icon',
            field=models.ImageField(blank=True, help_text='Image Size: width=40px, height=40px', null=True, upload_to='service/'),
        ),
        migrations.AlterField(
            model_name='worktogether',
            name='image',
            field=models.ImageField(blank=True, help_text='Image Size: width=1140px, height=515px', null=True, upload_to='together/'),
        ),
    ]
