# Generated by Django 2.2.9 on 2020-01-20 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0068_auto_20200120_0618'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ProductCategory',
        ),
    ]
