# Generated by Django 2.2.9 on 2020-01-20 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0069_auto_20200120_0621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryDetail',
            new_name='ProductCategoryDetail',
        ),
    ]
