# Generated by Django 2.2.9 on 2020-01-20 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0070_auto_20200120_0624'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='ProductCategoryDetail',
            new_name='CategoryDetail',
        ),
    ]
