# Generated by Django 2.2.9 on 2020-03-17 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0071_auto_20200120_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('included_cost', models.TextField()),
                ('image', models.ImageField(help_text='Image Size: width=262px, height=489px', upload_to='tour/')),
                ('video', models.URLField(help_text='Please enter the url of the video from youtube or other sources')),
            ],
        ),
        migrations.CreateModel(
            name='TourDetailItinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='item.Tour')),
            ],
        ),
    ]
