# Generated by Django 2.2.9 on 2020-03-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0073_auto_20200322_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='gmail_url',
            field=models.URLField(blank=True, help_text="Please enter the url of your company's gmail", null=True),
        ),
    ]
