# Generated by Django 2.2.9 on 2020-03-22 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0074_companydetail_gmail_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GallerCategory',
            new_name='GalleryCategory',
        ),
    ]
