# Generated by Django 2.2.9 on 2020-03-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0075_auto_20200322_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
    ]
