# Generated by Django 2.2.9 on 2020-03-22 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0076_remove_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='included_cost',
        ),
        migrations.CreateModel(
            name='IncludedCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inc_tour', to='item.Tour')),
            ],
        ),
    ]
